version: "3.8"

services:
  database:
    image: postgres:16-alpine
    volumes:
      - ./database_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: backend
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy